/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedApplicationsRouteImport } from './routes/_authed/applications'
import { Route as AuthedApplicationsIndexRouteImport } from './routes/_authed/applications.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedApplicationsApplicationIdRouteImport } from './routes/_authed/applications.$applicationId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApplicationsRoute = AuthedApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApplicationsIndexRoute = AuthedApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedApplicationsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedApplicationsApplicationIdRoute =
  AuthedApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthedApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof AuthedApplicationsRouteWithChildren
  '/home': typeof AuthedHomeRoute
  '/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/applications/': typeof AuthedApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthedHomeRoute
  '/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/applications': typeof AuthedApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/applications': typeof AuthedApplicationsRouteWithChildren
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/applications/': typeof AuthedApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/home'
    | '/applications/$applicationId'
    | '/api/auth/$'
    | '/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/applications/$applicationId'
    | '/api/auth/$'
    | '/applications'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/applications'
    | '/_authed/home'
    | '/_authed/applications/$applicationId'
    | '/api/auth/$'
    | '/_authed/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/applications': {
      id: '/_authed/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthedApplicationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/applications/': {
      id: '/_authed/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthedApplicationsIndexRouteImport
      parentRoute: typeof AuthedApplicationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/applications/$applicationId': {
      id: '/_authed/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthedApplicationsRoute
    }
  }
}

interface AuthedApplicationsRouteChildren {
  AuthedApplicationsApplicationIdRoute: typeof AuthedApplicationsApplicationIdRoute
  AuthedApplicationsIndexRoute: typeof AuthedApplicationsIndexRoute
}

const AuthedApplicationsRouteChildren: AuthedApplicationsRouteChildren = {
  AuthedApplicationsApplicationIdRoute: AuthedApplicationsApplicationIdRoute,
  AuthedApplicationsIndexRoute: AuthedApplicationsIndexRoute,
}

const AuthedApplicationsRouteWithChildren =
  AuthedApplicationsRoute._addFileChildren(AuthedApplicationsRouteChildren)

interface AuthedRouteChildren {
  AuthedApplicationsRoute: typeof AuthedApplicationsRouteWithChildren
  AuthedHomeRoute: typeof AuthedHomeRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApplicationsRoute: AuthedApplicationsRouteWithChildren,
  AuthedHomeRoute: AuthedHomeRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
